version: '3'

services:
  web:
    build: .
    ports:
      - "80:5000"
    restart: always
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=production
    volumes:
      - ./flask_version:/app
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000"]
      interval: 30s
      timeout: 10s
      retries: 3 